export function levelList() {
    let levels = [
        {
            title: 'Beginners',
            value: 'Beginners'
        },
        {
            title: 'Beginners II',
            value: 'Beginners II'
        },
        {
            title: 'Beginners III',
            value: 'Beginners III'
        },
        {
            title: 'GCSE',
            value: 'GCSE'
        },
        {
            title: 'Pre Intermediate',
            value: 'Pre Intermediate'
        },
        {
            title: 'Intermediate',
            value: 'Intermediate'
        },
        {
            title: 'Upper Intermediate',
            value: 'Upper Intermediate'
        },
        {
            title: 'Advanced - Alevel',
            value: 'Advanced - Alevel'
        },
        {
            title: 'Proffesional',
            value: 'Proffesional'
        },
    ]
    return levels
}
export function servicesList() {
    let services = [
        {
            title: 'CLIENT NOW',
            value: 'CLIENT NOW'
        },
        {
            title: 'CLIENT PAST',
            value: 'CLIENT PAST'
        },
        {
            title: 'CLUB MEMBER',
            value: 'CLUB MEMBER'
        },
        {
            title: 'CLUB VISITOR',
            value: 'CLUB VISITOR'
        },
        {
            title: 'GROUPS',
            value: 'GROUPS'
        },
        {
            title: 'PRIVATE EXPRESS',
            value: 'PRIVATE EXPRESS'
        },
        {
            title: 'PRIVATE BLOCK',
            value: 'PRIVATE BLOCK'
        },
        {
            title: 'PRIVATE GCSE',
            value: 'PRIVATE GCSE'
        },
        {
            title: 'PRIVATE ALEVEL',
            value: 'PRIVATE ALEVEL'
        },
    ];
    return services
}
export function serviceByClientList() {
    let services = [
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'David Weir', 'DATE': '1/1/2009' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Tré Rouco', 'DATE': '6/2/2010' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Masha Richards', 'DATE': '1/3/2010' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Rob Grisby', 'DATE': '1/9/2013' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Avinash Jobanpruta', 'DATE': '1/6/2015' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Avinash Jobanpruta', 'DATE': '1/9/2015' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Nicola Fickling', 'DATE': '1/8/2016' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Cindy Rosengarten', 'DATE': '1/9/2016' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Mark Varilone', 'DATE': '1/9/2016' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Oliver Holloway', 'DATE': '1/9/2016' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Susie Blair', 'DATE': '1/9/2016' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Stacey Smith', 'DATE': '1/11/2016' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Michelle Hernandez', 'DATE': '1/1/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Mike Howlett', 'DATE': '1/1/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Paul Walsh', 'DATE': '1/1/2017' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Leila Davey', 'DATE': '1/2/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Malekzadeh', 'DATE': '1/2/2017' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Maryann Smithers', 'DATE': '1/5/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'michael lawrence', 'DATE': '1/5/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Oliver Kuzmanoski', 'DATE': '1/5/2017' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Sammie Hodgson', 'DATE': '1/5/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Mark Chilton', 'DATE': '1/6/2017' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Ian Alexander', 'DATE': '1/7/2017' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Neil Macgregor', 'DATE': '1/7/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Lily Verlander', 'DATE': '1/8/2017' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Michele Gibson', 'DATE': '1/8/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Roger Ponsford', 'DATE': '1/8/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Louise Ritchie', 'DATE': '1/9/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Sarah Rae', 'DATE': '1/9/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Sharon Campbell', 'DATE': '1/9/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Stephanie Tuffin', 'DATE': '1/9/2017' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Tim Hand', 'DATE': '1/9/2017' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Suzan Bahsaun', 'DATE': '1/10/2017' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Indigo Byles', 'DATE': '1/11/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Janet Welsh', 'DATE': '1/11/2017' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Karen Mitchell', 'DATE': '1/12/2017' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Robin McGuigan', 'DATE': '1/12/2017' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Anthony Oconnell', 'DATE': '1/1/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Natalie', 'DATE': '1/1/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Roger Welsh', 'DATE': '1/1/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Sean West', 'DATE': '1/1/2018' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Beverley Gibson', 'DATE': '1/2/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Chris Seaward', 'DATE': '1/2/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Jackie Cadwell', 'DATE': '1/2/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Susan Williams', 'DATE': '1/2/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Hilary Ball', 'DATE': '1/3/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Jessika Duggal', 'DATE': '1/3/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Keith Weaver', 'DATE': '1/3/2018' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Susan Williams', 'DATE': '1/3/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Susie Blair', 'DATE': '1/3/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Ellie Miles', 'DATE': '1/4/2018' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'James Benn', 'DATE': '1/4/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Sachin Jindal', 'DATE': '1/4/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Cassie Brown', 'DATE': '1/5/2018' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Cassie Brown', 'DATE': '1/5/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Christina Stevens', 'DATE': '1/5/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Victoria Dubey', 'DATE': '1/5/2018' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Lydia Bartlett', 'DATE': '1/6/2018' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Mo Carmody', 'DATE': '1/6/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Nick Holloway', 'DATE': '1/6/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Adam Martin', 'DATE': '1/7/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Alexandra Hunter-Dunn', 'DATE': '1/7/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Arthur Nichols', 'DATE': '1/7/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Linda Shelley', 'DATE': '1/7/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Nathan Harrison', 'DATE': '1/7/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Ross Williams', 'DATE': '1/7/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Aleksandra Urbanowicz', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Amal Patel', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Avinash Jobanpruta', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Christine Ciemka', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Danielle Cox', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Emma Knezevic', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Emma Walker', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Ian Floyd', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Janet Welsh', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Jenni Taylor', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Justina Bozyk', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Linda Kadlcova', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Meena Shankar', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Paul Briggs', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Pippa Debney', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Roger Welsh', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Tanya Daykin', 'DATE': '1/9/2018' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Andrew Truscott', 'DATE': '1/10/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Charlotte Gershon', 'DATE': '1/10/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Gary Tollick', 'DATE': '1/10/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Melissa Wilding', 'DATE': '1/10/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Richard Hollington', 'DATE': '1/10/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'George Pannell', 'DATE': '1/11/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Carly Mills', 'DATE': '1/12/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Lucy Boullin', 'DATE': '1/12/2018' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Petra Holubcová', 'DATE': '1/12/2018' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Becky Hill', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Ben Bridges', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Dominique Radclyffe', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Felina', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Jake Branni', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Jenny Levy', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Mitchell Garrett', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Soraya Anderson', 'DATE': '1/1/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Catherine Munteanu', 'DATE': '1/2/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Lynda Pewter', 'DATE': '1/2/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Paul Colvin', 'DATE': '1/2/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Stephanie Pullen', 'DATE': '1/2/2019' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': "Suzanne O'Beirne", 'DATE': '6/2/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Nancy Willis', 'DATE': '1/3/2019' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Shilpa Agarwal', 'DATE': '1/4/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Romana Funkeova', 'DATE': '1/5/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Angeliki Steleanisi', 'DATE': '1/6/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Janet Martin', 'DATE': '1/6/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Piers Crichton', 'DATE': '1/6/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Philip', 'DATE': '1/7/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Eve McBrinn', 'DATE': '1/8/2019' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'John Elbrow', 'DATE': '1/8/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Martin Piekarzz', 'DATE': '1/8/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Phillip Sharpes', 'DATE': '1/8/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Alasdair Hill', 'DATE': '1/9/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Andrew Malcolm', 'DATE': '1/9/2019' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Clare Tomlinson', 'DATE': '1/9/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Hannah Lachkovic', 'DATE': '1/9/2019' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Marta Olszewska', 'DATE': '1/9/2019' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Will Bennett', 'DATE': '1/9/2019' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Jonathan Zammint-Tabona', 'DATE': '1/10/2019' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Cathy Wise', 'DATE': '1/11/2019' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Anna Bennett ', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Claire Boult ', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Dean Moore', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Diana Daubney', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'John Gibson', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Laverne Towsend', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Louis Mills', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Sally Wilson', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Tatyana Soroko', 'DATE': '1/1/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Tré Rouco', 'DATE': '6/2/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Alice Reeve', 'DATE': '6/2/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Thomas Newman', 'DATE': '12/2/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Jacqueline Harrison', 'DATE': '12/2/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Michael Cope', 'DATE': '15/2/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Helen McGrath', 'DATE': '19/2/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Alireza Malekzadeh', 'DATE': '19/2/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Emily Nye-Dowling', 'DATE': '6/4/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Stafford David', 'DATE': '9/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Maddy Roberts', 'DATE': '9/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Lilly Turko', 'DATE': '9/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Joanna Kimber', 'DATE': '9/4/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Mariam Majid', 'DATE': '9/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Ann Mitchell', 'DATE': '3/5/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Catherine Michel', 'DATE': '9/9/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Joanne Molloy', 'DATE': '5/10/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Rachel Hughes', 'DATE': '5/10/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Laura Reeve', 'DATE': '5/10/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Finnbarr Lewis', 'DATE': '6/10/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Ayshe Sozen', 'DATE': '9/10/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Suzie Thomas', 'DATE': '10/10/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Mitchell Greetham', 'DATE': '5/12/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Rafal', 'DATE': '1/1/2021' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Rob Allison', 'DATE': '2/2/2021' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Gareth Farrell', 'DATE': '2/2/2021' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Ydania', 'DATE': '2/2/2021' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Gabriella Pap', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Niall McGarry', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Maria Virginia Monagas Dubuc', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Sima Haririan', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Anjenna', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Rebecca Cawston', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Janet Allison', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Duncan Richardson', 'DATE': '1/5/2021' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Nick Blake', 'DATE': '2/5/2021' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Slav Dimitrov', 'DATE': '2/5/2021' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Janice for Freddy', 'DATE': '3/5/2021' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Evgeniya Bakalova', 'DATE': '3/5/2021' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Rebeca Kemble', 'DATE': '3/5/2021' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Elena Larkin', 'DATE': '3/5/2021' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Rebeca Cuadros ', 'DATE': '1/6/2021' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Neil Herbert', 'DATE': '1/10/2021' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Rocio Cossio', 'DATE': '3/10/2021' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Lydia Bartlett', 'DATE': '13/3/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Vanessa Burrows', 'DATE': '14/4/2020' },
        { 'SERVICE NAME': 'Spanish Club Member', 'CLIENT NAME': 'Charlotte Williamson', 'DATE': '15/2/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Carla Dema', 'DATE': '15/3/2021' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Marie Butcher', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Joelle Fry', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Jamie Wickins', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Katie Whales', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Laura Fell', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Heather Maddock', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Casia Zajac', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Susan Maclean', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Kristy Johncock', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Vijay Srikanth', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Sharon Mason', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Peter Motis', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Caroline Burns', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Pauline Dorking', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Soltan Khazal', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Caroline Vize', 'DATE': '15/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Satvinder Dobb', 'DATE': '15/5/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Lara Watkins-Truitt ', 'DATE': '15/9/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Katy Woodman', 'DATE': '15/9/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Lame Verre', 'DATE': '15/9/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Kate Woodley', 'DATE': '15/9/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Maddy Roberts', 'DATE': '15/9/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Michael Green', 'DATE': '16/4/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Edward Newton', 'DATE': '16/4/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Lucy Garrett', 'DATE': '20/2/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Lear Marett', 'DATE': '20/3/2021' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Rochelle Strooh', 'DATE': '20/4/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Charlotte Williamson', 'DATE': '20/4/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Patrick Stallion', 'DATE': '20/8/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Peter Feloy', 'DATE': '20/8/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Anne Simpson', 'DATE': '20/9/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Susan George', 'DATE': '20/9/2020' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Susan Beresford', 'DATE': '25/7/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Vivien Wang', 'DATE': '25/7/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Sajini Wijetilleka', 'DATE': '25/7/2020' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Rena Ghotey', 'DATE': '27/7/2020' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Robert Taylor', 'DATE': '28/7/2020' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Sharon Betts', 'DATE': '28/7/2020' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Andrew Rawlings', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Charlotte Creswick Kelly', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Charlotte Gershon', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Chris Piney', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Claire McDonnell', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'Clint Chapman', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Derek Williamson', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Elina Rangelova', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Ian Bull', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Jake Gill', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Private', 'CLIENT NAME': 'James Wright', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Jane Dutton', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Jason Brooker', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Jay Hurley', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Jill Coburn', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Jo-Anna', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Joanna Billups', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Katherine Stevenson', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Kim Dawson', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Lee Wells', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Marggie Sherriff', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Marina Hilding Ohlsson', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Mark Robinson ', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Matt', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Matthew Truelove', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Maya Stone', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Ruth Dawson', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Samer Humadi', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Stephanie Davis', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Group', 'CLIENT NAME': 'Stephen Moonan', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Steve Harrowell', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Suzanne Cano', 'DATE': '' },
        { 'SERVICE NAME': '', 'CLIENT NAME': 'Tony Vinelot', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish GCSE', 'CLIENT NAME': 'Zina Botha / Dasha Daughter', 'DATE': '' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Francesca Henry', 'DATE': '' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Laura Reeve', 'DATE': '' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Joanne Molloy', 'DATE': '' },
        { 'SERVICE NAME': 'Spanish Club 1 Visit', 'CLIENT NAME': 'Ana Maria', 'DATE': '' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Daniela', 'DATE': '' },
        { 'SERVICE NAME': 'Express Classes', 'CLIENT NAME': 'Ann Mitchell', 'DATE': '4/10/2021' },
        { 'SERVICE NAME': 'CLUB VISITOR', 'CLIENT NAME': 'Teresa Martin', 'DATE': '4/10/2021' },
        { 'SERVICE NAME': 'PRIVATE BLOCK', 'CLIENT NAME': 'Rebecca Wilkinson', 'DATE': '4/10/2021' },
        { 'SERVICE NAME': 'GROUPS', 'CLIENT NAME': 'Jason Gregory', 'DATE': '' },
        { 'SERVICE NAME': 'PRIVATE EXPRESS', 'CLIENT NAME': 'Sophie Redvers', 'DATE': '' },
        { 'SERVICE NAME': 'GROUPS', 'CLIENT NAME': 'Belinda Bradley', 'DATE': '4/10/2021' },
        { 'SERVICE NAME': 'GROUPS', 'CLIENT NAME': 'John Gibson and Katie Mann', 'DATE': '4/10/2021' },
        { 'SERVICE NAME': 'PRIVATE GCSE', 'CLIENT NAME': 'Fung-yee Chan', 'DATE': '5/01/2021' },

    ];
    return services
}
export function clientsList() {
    let data = [
        {
            KEY: 1,
            NAME: 'Ann Mitchell',
            TELEPHONE: '7767355991',
            EMAIL: 'ann.mitchell@travelcounsellors.com',
            SERVICE: ['Enquiry'],
            LEVEL: 'Beginners',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 2,
            NAME: 'Anne Simpson',
            TELEPHONE: '7910110483',
            EMAIL: 'anne.a.simpson@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "Facebook",
            CITY: 'West Ewell',
            ADDRESS: '54 Gibraltar Crescent, West Ewell Kt19 9BT',
            COMMENTS: ""
        },
        {
            KEY: 3,
            NAME: 'Avinash Jobanpruta',
            TELEPHONE: '7714756813',
            EMAIL: 'a.jobanputra@btinternet.com',
            SERVICE: ['Client'],
            LEVEL: 'Pre Intermediate',
            FOUND: "private client",
            CITY: 'Chessington',
            ADDRESS: '163 Chantry Road, Chessington KT9 1XD',
            COMMENTS: ""
        },
        {
            KEY: 4,
            NAME: 'Beverley Gibson',
            TELEPHONE: '7775816582',
            EMAIL: 'beverleyjill@icloud.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Upper Intermediate',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 5,
            NAME: 'Catherine Michel',
            TELEPHONE: '7854466872',
            EMAIL: 'catherinemichel@hotmail.co.uk',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Intermediate',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 6,
            NAME: 'Chris Piney',
            TELEPHONE: '7538637436',
            EMAIL: 'chris@cheamboilers.co.uk',
            SERVICE: ['Enquiry'],
            LEVEL: 'Beginners',
            FOUND: "WOM in the gym",
            CITY: 'Cheam',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 7,
            NAME: 'David Stafford ',
            TELEPHONE: '7795251564',
            EMAIL: 'david.stafford@syngenta.com',
            SERVICE: ['Client'],
            LEVEL: 'Upper Intermediate',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 8,
            NAME: 'David Weir',
            TELEPHONE: '7709121638',
            EMAIL: 'davidianweir@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Intermediate',
            FOUND: "",
            CITY: '',
            ADDRESS: '139 Cotterill Road Surbiton KT9',
            COMMENTS: ""
        },
        {
            KEY: 9,
            NAME: 'Edward Newton',
            TELEPHONE: '7958960667',
            EMAIL: 'enewton@prospectconsulting.co.uk',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "MP letter promotional, he is 71 years of age.",
            CITY: 'Kingston',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 10,
            NAME: 'Elena Larkin',
            TELEPHONE: '7894235135',
            EMAIL: 'elena@tambotravel.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Advanced',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 11,
            NAME: 'Eve McBrinn',
            TELEPHONE: '7500034857',
            EMAIL: 'mcbrinneve@gmail.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Upper Intermediate',
            FOUND: "googled Spanish Lesosns ",
            CITY: 'Kingston',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 12,
            NAME: 'Evgeniya Bakalova',
            TELEPHONE: '7917867036',
            EMAIL: 'evgeniyabakalova@gmail.com',
            SERVICE: ['Past Client'],
            LEVEL: 'Beginners',
            FOUND: "",
            CITY: '',
            ADDRESS: '18 Nelson Road, Wimbledon, London, SW19 1HT',
            COMMENTS: ""
        },
        {
            KEY: 13,
            NAME: 'Finnbarr Lewis',
            TELEPHONE: '7981141352',
            EMAIL: 'finnmonty@gmail.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Upper Intermediate',
            FOUND: "",
            CITY: '',
            ADDRESS: '133 Canbury Park Road Kingston KT2 6LH',
            COMMENTS: ""
        },
        {
            KEY: 14,
            NAME: 'Gabriella Pap',
            TELEPHONE: '7968599599',
            EMAIL: 'gaby.j.pap@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "Facebook",
            CITY: '',
            ADDRESS: '2 CEDAR Walk, Claygate,Surrey, KT10 0RN ',
            COMMENTS: "Age 40-50"
        },
        {
            KEY: 15,
            NAME: 'Gary Tollick',
            TELEPHONE: '7843273519',
            EMAIL: 'gtollick@hotmail.com',
            SERVICE: ['Enquiry'],
            LEVEL: 'Beginners',
            FOUND: "sign outside",
            CITY: 'Chessington',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 16,
            NAME: 'Ian Bull',
            TELEPHONE: '07572 455559',
            EMAIL: 'ianbull125@gmail.com',
            SERVICE: ['Enquiry'],
            LEVEL: '',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 17,
            NAME: 'Jacqueline Harrison',
            TELEPHONE: '7984129732',
            EMAIL: 'jacqueline@jacquelineharrison.co.uk',
            SERVICE: ['Client'],
            LEVEL: 'Beginners II',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "studied on an adult education programme for 1 year"
        },
        {
            KEY: 18,
            NAME: 'Janet Allison',
            TELEPHONE: '7739012145',
            EMAIL: 'janetallison@gmail.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Beginners II',
            FOUND: "Facebook ",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "I have tried a classroom approach and some on line classes, feel I understand more, but with COVID no chance to use it for real, I would like more information on prices"
        },
        {
            KEY: 19,
            NAME: 'Janet Welsh',
            TELEPHONE: '7931534450',
            EMAIL: 'janet.welsh1@ntlworld.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Upper Intermediate',
            FOUND: "googled",
            CITY: 'Claygate',
            ADDRESS: '4 Oakhill, Claygate KT10 0TG',
            COMMENTS: ""
        },
        {
            KEY: 20,
            NAME: 'Joanne Molloy',
            TELEPHONE: '7598260805',
            EMAIL: 'molloy.joanne@gmail.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Beginners II',
            FOUND: "Facebook",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 21,
            NAME: 'Karen Mitchell',
            TELEPHONE: '7983327228',
            EMAIL: 'karen_a_mitchell@hotmail.co.uk',
            SERVICE: ['Enquiry'],
            LEVEL: 'Beginners',
            FOUND: "sign outside house",
            CITY: 'Morden',
            ADDRESS: '',
            COMMENTS: "Hello My boyfriend and I are complete beginners but are both keen to learn Spanish. I was wondering if you could let me know your availability for private lessons and the costs."
        },
        {
            KEY: 22,
            NAME: 'Katy Woodman',
            TELEPHONE: '7949562454',
            EMAIL: 'katywoodman@googlemail.com',
            SERVICE: ['Past Client'],
            LEVEL: 'Beginners',
            FOUND: "Google Spanish lessons",
            CITY: '',
            ADDRESS: '12 Woodside Road New Malden KT3 3AH',
            COMMENTS: "I studied spanish O'level but that was 30 years ago. I would like to improve my conversational spanish as I intend visiting spain a lot in the future for golf/food trips with friends and would like to be more lingual."
        },
        {
            KEY: 23,
            NAME: 'Lilly Turko',
            TELEPHONE: '7738239404',
            EMAIL: 'turkolilly3@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "googled Spanish Lessons",
            CITY: 'Chessington',
            ADDRESS: 'Douglas Villa, 2A Douglas Avenue, New Malden KT36HT',
            COMMENTS: "wants to travel to Latin America"
        },
        {
            KEY: 24,
            NAME: 'Lucy Garrett',
            TELEPHONE: '7939227995',
            EMAIL: 'lucyasgarrett@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Intermediate',
            FOUND: "website",
            CITY: 'Guildfore',
            ADDRESS: '61 Drummond Road, Guildford, GU1 4NX',
            COMMENTS: "lived in Peru, works for the UNU"
        },
        {
            KEY: 25,
            NAME: 'Maddy Roberts',
            TELEPHONE: '7813211880',
            EMAIL: 'maddyrobertspt@gmail.com',
            SERVICE: ['Enquiry'],
            LEVEL: 'Pre Intermediate',
            FOUND: "googled Spanish lessons near me",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "I am potentially interested in starting up with learning Spanish again, but not really sure where to start. I learnt Spanish to a reasonable level, doing GCSE at school and continuing with an additional 3 years at university (this was not my main subject), but it has been 20 years since then!. I recently picked up Duolingo and have been dabbling with that, so it is slowly coming back to me, but I think I'd like to do more and certainly force myself to do more conversations. I might be interested in trying to do some exams again or perhaps just learning enough so I can be confident to speak the language next time I am over in Tenerife."
        },
        {
            KEY: 26,
            NAME: 'Maryann Smithers',
            TELEPHONE: '7882752822',
            EMAIL: 'maryann@smutley.co.uk',
            SERVICE: ['Enquiry'],
            LEVEL: '',
            FOUND: "",
            CITY: 'West Molesey',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 27,
            NAME: 'Masha Richards',
            TELEPHONE: '7919100932',
            EMAIL: 'masha_richards@aol.co.uk',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "WOM Michele Gibson",
            CITY: 'Cobham',
            ADDRESS: '',
            COMMENTS: "m_eremina@yahoo.com"
        },
        {
            KEY: 28,
            NAME: 'Michael Green',
            TELEPHONE: '7713632272',
            EMAIL: 'mbgreen13@hotmail.co.uk',
            SERVICE: ['Club Member'],
            LEVEL: 'Intermediate',
            FOUND: "MP letter and interested in the Spanish Club",
            CITY: 'Surbiton',
            ADDRESS: '2 Copse Glade, Surbiton, KT6 6QB',
            COMMENTS: ""
        },
        {
            KEY: 29,
            NAME: 'Michele Gibson',
            TELEPHONE: '7766462372',
            EMAIL: 'mahanley@yahoo.com',
            SERVICE: ['Client'],
            LEVEL: 'Advanced Beginners',
            FOUND: "googled Spanish lessons in surrey",
            CITY: 'Oxshot',
            ADDRESS: '7 Goldrings Road, Oxshott, KT22 0QP',
            COMMENTS: ""
        },
        {
            KEY: 30,
            NAME: 'Mitchell Greetham',
            TELEPHONE: '7595695934',
            EMAIL: 'mitchellgreetham@live.com',
            SERVICE: [''],
            LEVEL: 'Beginners',
            FOUND: "outside banner",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "wants to learn with wife"
        },
        {
            KEY: 31,
            NAME: 'Neil Herbert',
            TELEPHONE: '7512755413',
            EMAIL: 'neilherbert3@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "google spanish lessons",
            CITY: '',
            ADDRESS: '1 Amis Avenue West Ewell Epsom KT9 9HZ',
            COMMENTS: ""
        },
        {
            KEY: 32,
            NAME: 'Niall McGarry',
            TELEPHONE: '7944211080',
            EMAIL: 'niall.mcgarry@btopenworld.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners II',
            FOUND: "Sign outsite",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "Callums father 50-70    +57 3102949510   I am buying this as a Xmas present for my father. My father is now retired and has always been interested in Spain and also Latin America. He should have knowledge of the basics as he spent his summers in Spain as a child. He even completed a GCSE in Spanish over 10/15 years ago. However, I think he will be very rusty as he has had no need to use Spanish for many years now. One of the reasons I am buying my father Spanish classes for Xmas is that I live in Colombia and it would be great for him to be able to communicate with my partner's family. Seasons greetings, Callum :) PS Please don't contact my Dad until after 25th December Email the voucher to callum.mcgarry@gmail.com instead "
        },
        {
            KEY: 33,
            NAME: 'Nick Blake',
            TELEPHONE: '7775684936',
            EMAIL: 'nick.blake@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "Google Spanish lessons near me",
            CITY: 'Walton on Thames',
            ADDRESS: '20 Walton Park, Kt12 eEU',
            COMMENTS: ""
        },
        {
            KEY: 34,
            NAME: 'Nick Holloway',
            TELEPHONE: '7971191881',
            EMAIL: 'nick.holloway@cantab.net',
            SERVICE: ['Club Member'],
            LEVEL: 'Advanced',
            FOUND: "googled spanish classes surrey",
            CITY: 'Leatherhead',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 35,
            NAME: 'Peter Feloy',
            TELEPHONE: '7482627695',
            EMAIL: 'peterfeloy@gmail.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Beginners',
            FOUND: "Googled Spanish Lessons in Surrey",
            CITY: 'Fetcham',
            ADDRESS: 'Patchpenny, River Lane, Fetcham KT22 9RP',
            COMMENTS: ""
        },
        {
            KEY: 36,
            NAME: 'Phillip Sharpes',
            TELEPHONE: '7730671997',
            EMAIL: 'phillipsharpes1705@gmail.com',
            SERVICE: [''],
            LEVEL: 'Beginners',
            FOUND: "googles Spanish Lessons in Surrey",
            CITY: 'Hinchley Wood',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 37,
            NAME: 'Rebeca Cuadros ',
            TELEPHONE: '51-956765188',
            EMAIL: 'rebeca_noemic@hotmail.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Advanced',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 38,
            NAME: 'Rebeca Kemble',
            TELEPHONE: '7714429590',
            EMAIL: 'rebecakemble@outlook.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "googled Spanish lessons in surrey",
            CITY: 'Tadworth',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 39,
            NAME: 'Rebecca Cawston',
            TELEPHONE: '7815772641',
            EMAIL: 'r_cawston@yahoo.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Intermediate',
            FOUND: "club for her mother",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "Im writing on behalf of my mum who is 76 - she has spoken Spanish on and off for many years so I would say she is intermediate level."
        },
        {
            KEY: 40,
            NAME: 'Rob Allison',
            TELEPHONE: '07958 542044',
            EMAIL: 'rob@thamesdesignandbuild.com',
            SERVICE: ['Client'],
            LEVEL: 'Intermediate',
            FOUND: "Saw the advert outside the house",
            CITY: '',
            ADDRESS: 'Ditton Garages, Southville Road, Thames Ditton KT7 0UL',
            COMMENTS: "www.thamesdesignandbuild.com"
        },
        {
            KEY: 41,
            NAME: 'Roger Welsh',
            TELEPHONE: '79879883526',
            EMAIL: 'roger.welsh@ntlworld.com',
            SERVICE: ['Club Member'],
            LEVEL: 'Upper Intermediate',
            FOUND: "google search",
            CITY: 'Claygate',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 42,
            NAME: 'Sima Haririan',
            TELEPHONE: '7853153040',
            EMAIL: 'simahari@hotmail.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Beginners II',
            FOUND: "club member from Richmond",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "I can speak Spanish and be understood but not always grammatically correct especially using verbs. I have a good level of vocabulary My ambition is to sit GCSE Spanish and help my son who will be taking his GCSE next year "
        },
        {
            KEY: 43,
            NAME: 'Slav Dimitrov',
            TELEPHONE: '7473710065',
            EMAIL: 'kalakhan881031@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "googled spanish lessons near me",
            CITY: '',
            ADDRESS: '23 Hollingsworth Court, Surbiton, KT6 6SH',
            COMMENTS: "studied on his own"
        },
        {
            KEY: 44,
            NAME: 'Stephen Moonan',
            TELEPHONE: '7771378280',
            EMAIL: 'stephen.noonan@mi-steel.co.uk',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Intermediate',
            FOUND: "googled Spanish lessons Chessington",
            CITY: 'Chessington',
            ADDRESS: '',
            COMMENTS: "I took DELE A2 last November based on book/internet/podcast self study, and spent a few months in Spain earlier this year. I'm interested in taking the next step. Looks like I've missed the start of the lessons for Intermediate, but I'd be interested in observing a class so I know what to expect for next time."
        },
        {
            KEY: 45,
            NAME: 'Suzie Thomas',
            TELEPHONE: '7769703713',
            EMAIL: 'suzannesqueezethomas@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "googled Spanish Lessons Surrey",
            CITY: '',
            ADDRESS: '18 Basing Way, Thames Ditton, KT7 0NX',
            COMMENTS: "Self taught since March. I know quite a lot of vocabulary and present tense verbs. I have begun studying other tenses also. I have very little speaking, listening practice."
        },
        {
            KEY: 46,
            NAME: 'Ydania',
            TELEPHONE: '584144287166',
            EMAIL: 'ydaniacastillo@gmail.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Advanced',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 47,
            NAME: 'Teresa Martin',
            TELEPHONE: '41-0799488933',
            EMAIL: 'teresamartinfdz@hotmail.com',
            SERVICE: ['Club Visitor'],
            LEVEL: 'Proffesional',
            FOUND: "amiga de Gaby",
            CITY: '',
            ADDRESS: '',
            COMMENTS: ""
        },
        {
            KEY: 48,
            NAME: 'Rebecca Wilkinson',
            TELEPHONE: '7908169834',
            EMAIL: 'rwmay10@gmail.com',
            SERVICE: ['Private Block Classes'],
            LEVEL: 'Intermediate',
            FOUND: "goggled spanish lessons near me",
            CITY: 'Epsom',
            ADDRESS: '',
            COMMENTS: "lives in Valencia but wants to learn online"
        },
        {
            KEY: 49,
            NAME: 'Jason Gregory',
            TELEPHONE: '7454566775',
            EMAIL: 'jason.gregory51@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'Beginners II',
            FOUND: "",
            CITY: '',
            ADDRESS: '10 Westwands Ct, Bridge Road, East Molesey ',
            COMMENTS: ""
        },
        {
            KEY: 50,
            NAME: 'Sophie Redvers',
            TELEPHONE: '',
            EMAIL: 'sophie@redvers.org.uk',
            SERVICE: ['Enquiry'],
            LEVEL: 'Intermediate',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "university student doing Spanish and French in Birmingham"
        },
        {
            KEY: 51,
            NAME: 'Belinda Bradley',
            TELEPHONE: '7450612123',
            EMAIL: 'belindabradley1@gmail.com',
            SERVICE: ['Enquiry'],
            LEVEL: 'Beginners',
            FOUND: "",
            CITY: '',
            ADDRESS: '',
            COMMENTS: "google spanish language classes"
        },
        {
            KEY: 52,
            NAME: 'John Gibson and Katie Mann',
            TELEPHONE: '7876222352',
            EMAIL: 'j.gibbo729m@yahoo.co.uk',
            SERVICE: ['Client'],
            LEVEL: 'Beginners',
            FOUND: "sign outside the house",
            CITY: '',
            ADDRESS: '57 Malden Way New malden KT3 6EA',
            COMMENTS: "is studying with his wife Katie Mann"
        },
        {
            KEY: 53,
            NAME: 'Fung-yee Chan',
            TELEPHONE: '07500 904 325',
            EMAIL: 'fungyeelee41@gmail.com',
            SERVICE: ['Client'],
            LEVEL: 'GCSE',
            FOUND: "sign outside house",
            CITY: '',
            ADDRESS: '14 Meadow Way, Chessington, Surrey, KT9 1AS',
            COMMENTS: "daughter Anna GCSE"
        }
    ];
    return data;
}